### ISSUE TITLE
Unclear on how to use graphics::* functions.

### ISSUE THREAD

**Issue by Phrohdoh** [PistonDevelopers/graphics#1010]
Using `graphics` with `piston_window` where am I supposed to get this matrix when I don't have to setup a matrix to begin with?
http://docs.piston.rs/piston_window/graphics/fn.line.html

References:
http://docs.piston.rs/piston_window/graphics/trait.Graphics.html
http://docs.piston.rs/piston_window/glutin_window/struct.GlutinWindow.html
http://docs.piston.rs/piston_window/window/struct.WindowSettings.html

And http://docs.piston.rs/piston_window/vecmath_lib/type.Matrix2x3.html doesn't even exist.

**Comment by bvssvni** [comment]
`Matrix2x3` is declared [here](http://docs.piston.rs/piston_window/vecmath/type.Matrix2x3.html). The url was broken because `graphics` imported it as `vecmath_lib`. This might be a bug in rustdoc.

`piston_window` reexports `graphics` at top level, so when you use `piston_window::*;` you get all the graphics methods.

The matrix is an array `[[x0, y0, t0], [x1, y1, t1]]`. Usually you use `c.transform` where `c` is a `Context`. This transforms to point space such that rendering is consistent across retina and non-retina screens. To construct a `Context`, you either call `.draw_2d(|c, g| { ... })` on `PistonWindow` event like [here](https://github.com/PistonDevelopers/piston-examples/blob/master/src/image.rs#L25), or you can call `gl.draw(args.viewport(), |c, g| { ... })` like [here](https://github.com/PistonDevelopers/piston-examples/blob/master/user_input/src/main.rs#L82).

**Comment by Phrohdoh** [comment]
Thank you, this is quite helpful.
Would you accept a PR to `piston_window` that contains a working example once I get a bit further along with this?

**Comment by bvssvni** [comment]
@Phrohdoh That would be nice!
