### ISSUE TITLE
Add more detailed docs to required methods in main traits like Graphics

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/graphics#1020]
Perhaps we could make the `Graphics` trait a little more inviting by offering a more detailed description of what is required when implementing the required methods.

For example, a user might want to use conrod with their project that uses a different graphics system, so they take a look at the `Graphics` trait docs to see if they can adapt it to their backend. If they're a graphics newbie like myself, they might be unsure about what the `tri_list` methods should do, what the data should look like when passed to the given function, etc. As this is a core part of the piston API, perhaps some more details could be useful. Some ideas:
- Provide a brief description of what a tri_list is, what it's used for, why we chose it over alternative methods, and when it is called.
- A small example of what the data looks like in the array and how that maps to a basic example (maybe some shape).
- A link to a pre-existing implementation for a backend so that the user has an example.
- Links for further reading on why we draw triangles.

**Comment by bvssvni** [comment]
Some thoughts:

- `tri_list` is a list of triangles, as opposed to `tri_strip` where a new triangle uses the last edge of the previous triangle. A list of triangles can describe geometry that is separated, while a strip of triangles is continuous. List of triangles were chosen for flexibility and some initial tests showed that the performance difference was negligible for simple 2D. A `tri_strip` method might be added later if it turns out to be a big performance improvement.
- The data is split into vertex positions `[x0, y0, x1, y1, ...]` and vertex colors `[r0, g0, b0, a0, r1, g1, b1, a1, ...]`.
- An example graphics backend, using raw OpenGL commands, can be found [here].
- The reason piston-graphics uses triangles is because they are supported by all GPUs and easy to implement in various shaders. By building the abstraction on top of triangles, the 2D graphics can render faster compared to CPU rasterized 2D graphics. A tradeoff is that concave polygons must use the stencil buffer to do clipping. Piston-Graphics renders convex polygons for performance reasons, and requires a separate algorithm for concave polygons.
