### ISSUE TITLE
Improve documentation for graphics::rectangle

### ISSUE THREAD

**Issue by eterevsky** [PistonDevelopers/graphics#1061]
There are a few issues with the current documentation:
- What is the difference between `graphics::types::Rectangle` and `graphics::rectangle::Rectangle`?
- What is the canonical way to draw a rectangle? By using `graphics::rectangle()`? Or `Rectangle::draw()`? What about a rounded rectangle?
- Why does `graphics::types::Rectangle::draw()` have two rectangle parameters: self and rectangle?
- What are `x` and `y` arguments of `graphics::rectangle::centered_square()`? I mean, if it's a square and it is centered, it should have only one size.

I would be happy to fix this bug if I understood the logic myself.

**Comment by bvssvni** [comment]
- `types::Rectangle` is the type used internally in the library e.g. [Into<types::Rectangle>](https://github.com/PistonDevelopers/graphics/blob/master/src/lib.rs#L140)
- `graphics::rectangle` is a simplied version of `Rectangle::draw`. You call `Rectangle::new_round` to draw a round rectangle https://github.com/PistonDevelopers/graphics/blob/master/src/rectangle.rs#L74
- The rectangle shape is the thing that changes most frequently, so it is separated because the `Rectangle` object can be reused
- `x` and `y` are position coordinates

**Comment by eterevsky** [comment]
Thanks for the answers. I created a PR with some comments.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/graphics/pull/1062
