### ISSUE TITLE
Redesign `Graphics`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#958]
This is just a brainstorming issue for dumping ideas of how to improve the `Graphics` design.

**Comment by bvssvni** [comment]
piston-event was one time considering a dynamic structure that was dropped in favor for `Any`: https://github.com/PistonDevelopers/event/issues/314

If we expand on this idea, we could in principle send any combination of common vertex formats and parameters through a dynamic structure and this could match up directly to the shader parameters. Alternatively, this could match up to a set of buffers used for a rendering technique.

The idea might blur the distinction between 2D and 3D. I think it makes sense in the way the `Graphics` trait is about updating or sending data while the back-end is about buffering or processing the data.

**Comment by bvssvni** [comment]
Here is a suggestion of how a such dynamic structure might look like:

```Rust
pub struct Struct<'a> {
    pub fields: &'a [Data<'a>],
}

pub enum Data<'a> {
    Vec2Array(&'a str, &'a [[f32; 2]]),
    Vec3Array(&'a str, &'a [[f32; 3]]),
    Vec4Array(&'a str, &'a [[f32; 4]]),
    Mat4x4Array(&'a str, &'a [[[f32; 4]; 4]]),
    StructArray(&'a str, &'a [Struct<'a>]),
    
    Vec2(&'a str, &'a [[f32; 2]]),
    Vec3(&'a str, &'a [[f32; 3]]),
    Vec4(&'a str, &'a [[f32; 4]]),
    Mat4x4(&'a str, &'a [[f32; 4]; 4]),
    Struct(&'a str, &'a Struct<'a>),
}
```

**Comment by kie0tauB** [comment]
Hi, I love your project, I'm currently using it to write a simulation for a research paper.
We'd like to draw things to vector images instead of GL, but the triangles list in the Graphics trait doesn't work well in these formats: it yields huge files and doesn't raster well.

How about moving ellipses and lines to methods in trait Graphics with default implementation, that backends are free to redefine? Of course, triangle (OpenGL) -based backends wouldn't redefine anything, but it would allow me to write for instance a Cairo/PDF/SVG backend.

**Comment by bvssvni** [comment]
@kie0tauB `Graphics` already has these methods. You can override the `Graphics` trait and write vector shapes instead. Btw, if you make a such backend your free to host it under PistonDevelopers. :smile: 

I guess we can close this now, the issue is outdated.
