### ISSUE TITLE
Add `image::draw_many`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/graphics#976]
Take a slice of position and source rectangles. Could use the `Into` trait.

**Comment by bvssvni** [comment]
Alternative name is `draw_tiles` and use an indexed list of source rectangles.

**Comment by LaylConway** [comment]
Tiles seems a bit too domain specific, since there's a large variety of purposes beyond tiles that would benefit from this. The reason `draw_many` seemed like a good idea for me is because it seems the only thing that fits all the different purposes this function may have. Perhaps `draw_batch` more accurately describes the purpose of the function?

**Comment by bvssvni** [comment]
An idea is to create a separate `ImageBatch`.

Another idea is to have `image::draw_batch(&[Image], c.transform, g)`.

**Comment by LaylConway** [comment]
It could be beneficial to have a system similar to XNA's [`SpriteBatch`](https://msdn.microsoft.com/en-us/library/bb194908.aspx), meaning it could evolve into allowing more complex sorting, batching and drawing rules, however if there's a function that accepts an array of `(source, destination)` tuples and that draws in a single batch using that, implementing such a system on top of that wouldn't be too hard.

**Comment by bvssvni** [comment]
`draw_state`, `color` and `texture` is reused, so the optimal thing would be to have just rectangle and source rectangle in the batch.
